title: # a name for your Learning Lab course
tagline: # a short description for your Learning Lab course, displayed on the course catalog
description: # a longer description for your Learning Lab course, displayed on the course's landing page

# Repository setup
# The following section template information for the repository
# This will be used when the repository is crated for each individual learner

template:
  name:     Android Hello World Starter Code
  repo:     Hello-World-Android

# `before` block
# Actions to take place after the learner registers, but before they start interacting with their repo

before:
- type: # the type of action, full list at https://lab.github.com/docs/actions/
  # some actions require additional options, those should appear below `type:`
  # you can execute multiple actions in the `before` block

# Steps for the course
# A list of steps that take the learner through the course
# Create one step for each action that a learner will complete

steps:
Step 1: Install Android Studio
- title: Introducing Android Studio
  description: This step introduces you to the Android Studio IDE
  event: issue_comment
  actions: # a list of the actions that will occur when the step is triggered by an event
  - type: # the type of action, full list at https://lab.github.com/docs/actions

Step 2: Run default app on Emulator
- title: Introducing the Android Emulator
  description: This step introduces you to the Android Virtual Device manager that allows you to create an Emulator. You will run the Default app on the Emulator
#  event: # the event that will trigger the actions to be executed, full list at https://developer.github.com/v3/activity/events/types/
#  actions: # a list of the actions that will occur when the step is triggered by an event
#  - type: # the type of action, full list at https://lab.github.com/docs/actions

Step 3: Edit Layout with desired Views
 - title: Introducing XML Layouts
  description: You will now customize the layout to include a TextView and a Button
#  event: # the event that will trigger the actions to be executed, full list at https://developer.github.com/v3/activity/events/types/
#  actions: # a list of the actions that will occur when the step is triggered by an event
#  - type: # the type of action, full list at https://lab.github.com/docs/actions

Step 4: Enable Text to Speech
 - title:  Enable the Android TTS (Text to Speech) engine
  description: Make your device read the text in the TextView onCLick of a Button
#  event: # the event that will trigger the actions to be executed, full list at https://developer.github.com/v3/activity/events/types/
#  actions: # a list of the actions that will occur when the step is triggered by an event
#  - type: # the type of action, full list at https://lab.github.com/docs/actions

Step 5: Run App
 - title: Run your first App on the Emulator
  description: You will run the app on the Emulator to test it.
#  event: # the event that will trigger the actions to be executed, full list at https://developer.github.com/v3/activity/events/types/
#  actions: # a list of the actions that will occur when the step is triggered by an event
#  - type: # the type of action, full list at https://lab.github.com/docs/actions

